[project]
name = "chicago-invest-flow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "altair>=5.5.0",
    "geopandas>=1.0.1",
    "numpy>=2.2.0",
    "polars>=1.17.1",
]
